[package]
name = "omni-director"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
colored = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tempfile = "3.14.0"
warp = "0.3.7"
tokio = { version = "1.41.1", features = ["macros", "parking_lot", "rt", "rt-multi-thread"] }
chrono = "0.4.38"
debug_print = "1.0.0"
ez_logging = "0.1.4"
