[package]
name = "omni-director"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.93"
colored = "2.1.0"
lazy_static = "1.5.0"
phf = { version = "0.11.2", features = ["macros"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tempfile = "3.14.0"
thiserror = "2.0.3"
openssl = { version = "0.10.68", features = ["vendored"] }